### ISSUE TITLE
Request: Support modification of secure value in games that use it.

### ISSUE THREAD

**Issue by YodaDaCoda** [meladroit/svdt#1]
A number of games have a 'secure value' in their save data which is generated each time the game is saved. A copy of this value is stored on the 3DS itself, and if these values don't match when the game is started, then the save is declared corrupt. The offset at which this value is stored changes per game. 

More about this can be read here.
http://3dbrew.org/wiki/Anti_Savegame_Restore

Here is a GBATemp thread which gives the offsets of a number of games' save files.
https://gbatemp.net/threads/antisavegame-restore-secure-value-updater-ps-acnl-prw-ssb-xy-oras.396644/

It'd be handy if svdt were able to handle this so that we don't have to.

**Comment by meladroit** [comment]
There are a few things that make this tricky:
- We can't automatically detect title IDs for digital titles right now. (See <a href=https://github.com/meladroit/svdt/issues/2>issue #2</a>.) We could still get around this by looking up some identifier in the save file itself.
- As you mention, the offset is different for every game. However, if we can get the title, having a lookup table for secure value offsets wouldn't be too bad.
- It looks like for at least one game (SSB) multiple files have to be updated. (Is the secure value different for each file, in that case?) At least for SSB the offset is the same for both files, but I'll have to get the implementation right from the start to accommodate for worst possible scenarios (imagine if the secure value was on every single one of Rumble World's .dat files, and the offset was different for every single one of them ...)
- Rumble World's measure sounds especially tricky. However, at least it's not a proprietary compression/checksum, just zlib with CRC32. So, potentially possible to implement here.

I'll definitely give this some thought, but it's also definitely a comparative luxury. But at least it looks like the number of games using this (that people care about, anyway) is small?

**Comment by meladroit** [comment]
Partial resolution: v0.3-alpha implements support for this for games that aren't Rumble World. Getting close even on that, but just not quite there yet.

**Comment by YodaDaCoda** [comment]
You're a legend. Just wanna express my thanks. The speed of your development astounds me.

(I was working on my own tdvs replacement but hadn't even got as far as something that would compile when you released v0.1)

**Comment by meladroit** [comment]
Rumble World support seems to work in v0.3, based on personal testing. For all known anti-savegame restore games, svdt is now capable of automatically fetching the secure value in save data and using it to modify files when restored.
