### ISSUE TITLE
Return to HBL after emergency boot

### ISSUE THREAD

**Issue by SubstituteR** [meladroit/svdt#16]
Right now svdt will hang when it runs in emergency mode.  I think it would be nifty (not sure if possible) to return to the Homebrew Launcher after the dump is complete.

I know this would conflict with the current emergency mode dump (automatic instead of L shoulder.)
Is is possible to detect a fail on gfxInitDefault()?

**Comment by meladroit** [comment]
This would be interesting. I wonder how possible it is. r5 apparently brings [an 'exit-to-hblauncher' feature](https://twitter.com/smealum/status/650086740309487616) that should ['make it possible for devs to recover from crashes, and hopefully get _some_ debug information along the way'](https://twitter.com/smealum/status/650087670798905344), but I'm sceptical as to whether that includes this sort of crash.

It'd be interesting if svdt could send an exit-to-hbmenu signal if it doesn't get user input after a certain amount of time.

**Comment by SubstituteR** [comment]
I know R5 is better for this type of thing, but, would it be possible to preform the following logic.

if left shoulder pressed then dump save and exit after dump, do not call gfxInitDefault, else continue

How is the start button currently handling exit to homebrew? (does it just call an exit function?)

I know some homebrews use B and some use Select, so I do see this logic working, unless just dumping alone causes the hang.

**Comment by SubstituteR** [comment]
Also, I'd write it myself, but I can't seem to get the 3ds arm compiler to work on my Debian box (no wm or dm)

**Comment by suloku** [comment]
Why not detect if running under o3DS or n3ds? Since now we know the title id since bootup, if we are running under one of the problematic o3DS titles, just exit after backup/inject is performed before calling gfxInitDefault()

**Comment by meladroit** [comment]
Well, for one, I'm not sure it's necessarily an original/New 3DS thing—last time I checked, AC:NL didn't work with svdt for my N3DS, whereas other people have reported it working with svdt on their N3DS units. We'd need to compile all the reports out there of which titles work and which don't, but I don't think it's entirely consistent. I think people have reported varying success with MH4U/MH4G, for instance, regardless of O3DS/N3DS.

**Comment by suloku** [comment]
Maybe ninjhax 2.5 and its additional memory will fix these issues.

**Comment by SubstituteR** [comment]
Does gfxInitDefault() have a return code/state?
Additionally, make it not call gfxInitDefault if left shoulder button is pressed (?) (old emergency boot mode.)

**Comment by suloku** [comment]
Maybe we could make a special flag file that only works for o3DS owners that converts L/R buttons in old emergency mode?

gfxinit does not have any return value, but maybe gfxSharedMemory is not correctly allocated, we could check that to see if we need to exit after emergency mode is invoked, but I don't have a o3DS to dump gfxSharedMemory address to sd and see if it is correctly allocated.

**Comment by SubstituteR** [comment]
I have an o3ds, what would be the steps to dump the result of the allocation?

**Comment by suloku** [comment]
I've just realized that gfxSharedMemory is set when gfxinitdefault is called, so checking it prior to calling is no good either.

I don't think it will work, but try running this under SSB's (like svdt) and tell me:
1.- If a file called gfxlog.txt is created at the root of the sd card
2.- If it returns to HBL
(the program should write the file to sd and exit, but since it is called after gfxinitdefault() I expect it to crash and do nothing).

http://expirebox.com/download/eea3ee29d47e7e01fc1bb83c6ea892bd.html

**Comment by SubstituteR** [comment]
You are correct, crash and nothing is outputted.

**Comment by SubstituteR** [comment]
Hax 2.5 is out, this **should** be fixed.
