### ISSUE TITLE
Error when copying a file that is above x Mb

### ISSUE THREAD

**Issue by SubstituteR** [meladroit/svdt#17]
I believe this is more or less an issue with memory allocation (and running out of memory) than with svdt it's self.
However, assuming we know the memory allocation limit, what's to stop svdt from only allocating (and then copying) those bytes, and then releasing (or reusing) the allocated memory recursively for the length of the file being copied?

**Comment by SubstituteR** [comment]
Additionally, I do not know when the error begins, but it is between 1.1 Mb -> 10 Mb, since 1 Mb works fine, but 10 causes svdt to throw an error.

**Comment by meladroit** [comment]
I'm actually a little surprised that you're able to even copy a file that large. 1 MB or 1 Mb?

What game are you testing this under? I wouldn't expect many games to even allocate that much space for the save data partition.

It's not a RAM issue, if that's what you're talking about—it's an issue with the actual amount of storage allocated for the save data. (Even older ninjhax allowed for plenty of RAM for this kind of application.) If this is the multi-colour error, the filesystem service has thrown an error at svdt, and I'm pretty certain that that error corresponds to running out of space on the save data.

**Comment by SubstituteR** [comment]
1 **Mega**byte,
I tested with Mario Kart 7 (it has a decent amount of storage because of the replays folder.)
When I tried the 10 **Mega**byte file, it causes SVDT to "crash" (tell me I have to exit due to an error), but when relaunched shows the file.
I have not tested to see if the 10 MB file is 1:1 correct.

I used Standard Units for my sizes (1 **Mega**byte = 1 \* 10^6.)

**Comment by meladroit** [comment]
That is quite odd. Last time I tested trying to move too much data, usually the changes didn't end up sticking. It would be interesting to see if the 10 MB file is empty, partially copied, or just plain broken.

**Comment by SubstituteR** [comment]
I'll check after I finish dumping a friend's dead HDD.  
Also, Sm4sh is 100% working, so :smile:

**Comment by SubstituteR** [comment]
File is copied, but no bytes are written.  
Does SVDT alloc the entire sizeof the file?
Additionally, is it possible to detect free space in the game cart?

**Comment by SubstituteR** [comment]
I think I've figured out a basic way of cart size.  
Assuming they're all the same per game, we could find the cart size ourselves using recursion.
Then store that in a local db used by SVDT (via the title id) and simply compare bytes on cart vs total allowed bytes on cart to get the free bytes.

**Comment by meladroit** [comment]
I think we use ctrulib functions (i.e. FS:USER functions) when actually writing files to the save data, but you're right—we do malloc the entire size of the file (within copyFile() in main.c). That's probably not the smartest thing to do, but there should be enough memory available to us to copy most save files. Given that the 10 MB file on save data is empty, I'd say it's just that you ran out of free space—the OpenFile call probably succeeded, and then the WriteFile call probably failed.

The save data size is probably the same for any given title. Are you saying to keep writing bytes to the save data until we run out of free space? It seems rather time-intensive to do this for every game.

**Comment by SubstituteR** [comment]
Write 100mb -> on fail move to
Write 10mb -> on fail move to
Write 1mb -> on fail move go
Etc. Until we get to 1byte

**Comment by meladroit** [comment]
Sure, but doing this for every game seems a bit much. Keep in mind too that every time you run out of space, the filesystem becomes inoperable and svdt has to restart to access the filesystem properly again.

There must be a less brute-force way to do this. @suloku, do you know if we can use [FS:GetFreeBytes](http://3dbrew.org/wiki/FS:GetFreeBytes) on the save data archive? [Not able to test it myself at the moment.]

**Comment by SubstituteR** [comment]
I can try to build this myself,  
If I clone the source directory (and make file) and add the FS:GetFreeBytes snippet, I can compile correct?
I have the 3DS toolchain, but my linux box only has make and gcc/g++

**Comment by meladroit** [comment]
If you'd like to clone the git repo in full, and you already have ctrulib, devkitPro, etc., then it should work. (Not using CMake or anything fancy—gcc, make, and all that 3DS stuff should be enough ...) You may also need [3ds_portlibs](https://github.com/xerpi/3ds_portlibs) (I think suloku added on a zlib dependency at some point), if you don't have that already. Honestly, though, I'd recommend making a smaller test program if all you want is to test that snippet. Can't provide too much more support at the moment—sorry!

**Comment by suloku** [comment]
About fs:getfreebytes, I guess it should work? Profi2000 thinks so too. I'll try later if substituteCS doesn't do it before me.

ps: zlib dependency is for pokemon rumble world de/compresion.

UPDATE:
seems to work fine, but some tests should be done as files seem to be aligned or something. I tested with pokemon dream world save file, which is 692 bytes long, but it actually takes 1024 bytes of savedata space (checked free space before and after erasing the file). Should be tested but I guess they are rounded to the nearest potency of 2?

```
Result FSUSER_GetFreeBytes(Handle *handle, FS_archive archive, u64* free_bytes)
{
    u32 *cmdbuf = getThreadCommandBuffer();

    cmdbuf[0] = 0x08120080;
    cmdbuf[1] = archive.handleLow;
    cmdbuf[2] = archive.handleHigh;

    Result ret = 0;
    if((ret = svcSendSyncRequest(*handle)))
        return ret;

    if(free_bytes)
    {
        if(ret==0) *free_bytes=((u64)cmdbuf[3]<<32)|cmdbuf[2];
    }

    return cmdbuf[1];
}

Result getSaveFreeBytes(u64* size)
{
    Result ret;

    ret=FSUSER_GetFreeBytes(&saveGameFsHandle, saveGameArchive, size);
    if(ret!=0)return ret;

    if(*size)
        return ret;
    else
        return -1;
}
```

**Comment by suloku** [comment]
Posting this because probably edits don't appear as notifications (see my previous comment)

**Comment by meladroit** [comment]
Ah, I guess the zlib dependency is something I added on—sorry. I think I confused it with the blowfish stuff, which is in source rather than as another library.

512-byte blocks makes sense (encryption scheme? flash memory sector size? either way ...), so perhaps we should indicate space used/available in multiples of 512 B.

**Comment by suloku** [comment]
I made some test, they really seem to be 512 byte blocks.

**Comment by SubstituteR** [comment]
512B blocks might be either because of
The encryption method is using chunks of 512 bytes (and is padding data), which would be weird since it looks like it's [Blowfish](../blob/master/source/blowfish.c), and that uses [8 byte blocks](https://en.wikipedia.org/wiki/Blowfish_%28cipher%29).
Or
the Cartridge FS format is just really whack?
Eitherway, 512B sizes are better since each cartridge is guaranteed to have at least

512 \* n where n = ceiling(totalsize / 512)
