### ISSUE TITLE
Using svdt on PAD causes red screen

### ISSUE THREAD

**Issue by SubstituteR** [meladroit/svdt#18]
"I'm trying to extract the save file for Puzzle and Dragons: Z & Super Mario Edition.
Launching via Ironhax on 2.1 and tried the 2.0 boot.3dsx,
Using svdt and save_manager and selecting this title just results in a red screen on bottom, the application does not load at all.
This, by far, only happens to PAD, having used this on Pokémon XYORAS, Shuffle, Animal Crossing, Tomodachi Life, and SMT4 previously.
I've been having this issue for a while, even before the latest update (since 10.0.0).
Any ideas?"

[Source](https://www.reddit.com/r/3dshacks/comments/3q2c39/using_svdt_on_pad_causes_red_screen_new_3ds/)

**Comment by phecdaDia** [comment]
Just to quickly add something.  
I tried it out with the retail version and digital version on a N3DSXL 10.1.0-27E.using ironhax. You're unable to boot in emergency mode. I noticed the same happens when trying to access the savedata of "Hatsune Miku Project Mirai DX". It just stops at the red screen and freezes. Other games work fine.

**Comment by suloku** [comment]
There are lots of incompatible games, if the issue also happens with save manager it would seems the problem is not something that can be solved within svdt itself.
I'd say we wait until ninhax 2.5 is released, the new payload may solve all these incompatibilities.

**Comment by SubstituteR** [comment]
@suloku , may I have edit permission on the incompatible games?  I'm going to make a Google form where people can submit which game(s) don't work (including game version, 3ds firmware, and 3ds hardware.)

Edit:
I'm an idiot....I can already edit it.

**Comment by SubstituteR** [comment]
It seems from reports on GBATemp that 2.5 fixes incompatible games.
