### ISSUE TITLE
can't auto-detect digital title ID

### ISSUE THREAD

**Issue by meladroit** [meladroit/svdt#2]
When 3ds_hb_menu starts svdt, it uses the title ID for a target selected by the user. For gamecards (mediatype 0x2) the title ID is always zero. However, for digital titles, the title ID is of course unique for every game.

As far as I know 3ds_hb_menu does _not_ pass the selected title ID on to svdt, so svdt has to re-prompt the user for the title. The title ID is useful because it is used for accessing the title short description in exeFS:/icon, for naming save dumps, and could potentially be used for anti-anti savegame restore (only for digital games ...).

Some ideas:
- lookup tables for some kind of magic header
- having 3ds_hb_menu pass the title ID to svdt somehow
- implementing a service function that accesses the title ID (unfortunately APT:GetAppletInfo with NS_APPID = 0x300 won't work because APT somehow thinks the active appID is 0x101 [home menu])

**Comment by suloku** [comment]
For the record, some light is being thrown here about this: https://github.com/smealum/3ds_hb_menu/issues/27

EDIT: not just some light, getting the title ID works. This issue will close soon.

**Comment by meladroit** [comment]
Will close for now, pending suloku's pull request for ctrulib.

**Comment by suloku** [comment]
APT:GetProgramID has been added to ctrulib.
