### ISSUE TITLE
Can't restore a oras savegame

### ISSUE THREAD

**Issue by ghost** [meladroit/svdt#23]
Using rxtools, game instaled on emunand

I exported a save from ORAS, then  I edited with pkhex. When injecting the save the software ask for rewriting the secure value, I said yes, browsed to the main file folder and pressed y to inject, but now when I open the game I said something like the save datesare corrupted and don't works

I tried to re-inject the untouched save but I got the same result

Maybe I got this because I run a hackrom (rising ruby)?  it has the same titleid as vanilla OR

**Comment by suloku** [comment]
Works fine for me on Alpha Shapphire Digital copy (the code is the same for both).
Also make sure you are running svdt under emunand (use yellows8 hbl loader which is installed in cia format).

Try:
1.- Start a new game and save
2.- Run svdt under emunand
3.- Make sure you enable ASR when prompted
4.- Restore save
5.- Make sure you overwrite secure value when prompted.

This should work.

**Comment by ghost** [comment]
Nein, it doesn't work
I started a new game and saved after got my initial pkmn, backed up my save file and then I played a bit.
After that i went to yellows8 hbl loader, ran svdt and restaured the save, but it says the savedata is corrupt

im using a n3ds

**Comment by suloku** [comment]
Can you upload your save? I'll try to restore it to digital shapphire.

Meanwhile, you couls use savedatafile and delete secure vale since you are
in emunand

**Comment by ghost** [comment]
https://mega.nz/#!REsF3JLa!jWKz43RCNJa8KkB4bUaKAMdFTkGn8_83Ctrv1Z1MdNY
the main file

I use savedatafile to delete the secure value, but still it says the save is corrupt

**Comment by ghost** [comment]
hmm seems to be a hackrom related issue, with my animal crossing eshop install i can edit the save and restore without problems

I'll test a vanilla ruby and will test it

**Comment by ghost** [comment]
ok, I installed the vanilla oras and did the same steps like with AC but still the corrupt save error
Here is the save unmodified from my game (https://mega.nz/#!sR93UBqT!p6TaTaIp8lW_ft5L7WkyRSzbNCCG9JzH78lTvUxRpNw)

**Comment by suloku** [comment]
I've just restored that save to digital alpha sapphire and works, I don't know what's going wrong at your side.

**Comment by ghost** [comment]
Just found whats wrong. My ftp was using ASCII transfer instead of binary.
that fucks up the file and corrupts it (at least for me)
Now everything its ok, ty

2016-01-25 17:17 GMT+01:00 suloku notifications@github.com:

**Comment by suloku** [comment]
Glad you found the problem. You may close the issue then if it isn't much trouble.
