### ISSUE TITLE
Problem with buttoms ( sorry confusion i'm stupidxD)

### ISSUE THREAD

**Issue by ismaelct** [meladroit/svdt#25]
Hey hello, my problem is that when I go to delete or make another action, asking me to check with the botton "Select". The problem is that when I press restarts and returns to themehax loads the coldboot and choose Homebrew, I go to svdt and the file is not deleted.

Sorry bad english xD

**Comment by SubstituteR** [comment]
Are you hitting Start?

**Comment by ismaelct** [comment]
nope only select, how tells under
