### ISSUE TITLE
cursor forever go down

### ISSUE THREAD

**Issue by NathanDreamweaver** [meladroit/svdt#26]
The cursor forever goes down. if i try to make it go up, it goes down.

**Comment by Committee** [comment]
N3DS? If yes have  you tested your ZL/ZR Buttons?

**Comment by NathanDreamweaver** [comment]
i am on new 3ds and now only most of the times it goes forever down, not everytime i boot it. new 3ds xl 11.0 basehaxx. i have tried every button. i can do everything, as long as i don't try to go up, in that case, it goes instantly-down

**Comment by Committee** [comment]
have a strange feeling your ZL/ZR button is broken.

**Comment by NathanDreamweaver** [comment]
now it doesn't happen anymore
