### ISSUE TITLE
Fire Emblem Fates doesn't work correctly.

### ISSUE THREAD

**Issue by jman0125** [meladroit/svdt#27]
Fire Emblem Fates only gives a top black screen and a bottom red screen

**Comment by suloku** [comment]
Are you using this?

https://github.com/ihaveamac/9.6-dbgen-xmls/blob/master/README.md

**Comment by jman0125** [comment]
I think I found the problem, I'm using OoTHax.
https://reddit.com/r/3dshacks/comments/4qs4w6/confirmed_bug_oot_cartridge_causes_certain/

**Comment by suloku** [comment]
Then you might try pokemon picross ' entrypoint as a free alternative to run homebrew.

**Comment by jman0125** [comment]
Managed to get basehaxx working, which in turn allowed me to get humblehaxx working. I may get pichaxx when it comes out, just in case.

Anyway, the manager works amazingly now, so I'm just gonna close this.
